//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Duration { get; set; }
        public string UseTechnology { get; set; }
        public Nullable<int> CountProgrammers { get; set; }
        public Nullable<int> NominationId { get; set; }
        public Nullable<int> ExperienceId { get; set; }
    
        public virtual Experience Experience { get; set; }
        public virtual Nomination Nomination { get; set; }
    }
}
