//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Selection()
        {
            this.SelectionUser = new HashSet<SelectionUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> EducationId { get; set; }
        public Nullable<int> ExperienceId { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public Nullable<int> CertificationTestId { get; set; }
        public Nullable<int> SportProgrammingId { get; set; }
    
        public virtual CertificationTest CertificationTest { get; set; }
        public virtual Education Education { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual SportProgramming SportProgramming { get; set; }
        public virtual Training Training { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectionUser> SelectionUser { get; set; }
    }
}
