//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF.MyDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountCredit { get; set; }
        public Nullable<double> Evaluation { get; set; }
        public Nullable<int> NominationId { get; set; }
        public Nullable<int> EducationId { get; set; }
        public Nullable<int> KnowledgeId { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Knowledge Knowledge { get; set; }
        public virtual Nomination Nomination { get; set; }
    }
}
